# Generated by Django 4.2.7 on 2023-12-31 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_User', '0004_alter_useraccountmodel_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountmodel',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000000000000, max_length=12),
        ),
    ]
